[workspace]
authors = ["Aarash Zakeri <izear21@gmail.com>"]
channels = ["conda-forge"]
name = "totally-not-a-bot"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
format = { cmd = [
    "ruff",
    "check",
    "--select",
    "I",
    "--fix",
    "&&",
    "ruff",
    "format",
    "--config",
    ".ruff.toml",
    "./"
]}

[dependencies]
fastmcp = ">=3.2.4,<4"
"discord.py" = ">=2.3.2,<3"
pydantic = ">=2.13.3,<3"
ruff = ">=0.15.11,<0.16"
